
package com.axonivy.connectivity.soap.interceptor.client;

import javax.annotation.Generated;
import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-09-13T13:31:43.815+02:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "BusinessException", targetNamespace = "ch.ivyteam.ivy.webservice.process")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-09-13T13:31:43.815+02:00", comments = "Apache CXF 3.3.2")
public class WebServiceProcessBusinessException extends Exception {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-09-13T13:31:43.815+02:00")
    private java.lang.String businessException;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-09-13T13:31:43.815+02:00")
    public WebServiceProcessBusinessException() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-09-13T13:31:43.815+02:00")
    public WebServiceProcessBusinessException(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-09-13T13:31:43.815+02:00")
    public WebServiceProcessBusinessException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-09-13T13:31:43.815+02:00")
    public WebServiceProcessBusinessException(String message, java.lang.String businessException) {
        super(message);
        this.businessException = businessException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-09-13T13:31:43.815+02:00")
    public WebServiceProcessBusinessException(String message, java.lang.String businessException, java.lang.Throwable cause) {
        super(message, cause);
        this.businessException = businessException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-09-13T13:31:43.815+02:00")
    public java.lang.String getFaultInfo() {
        return this.businessException;
    }
}
