/*
 * TripPin service is a sample service for OData V4.
 * This service is located at [https://services.odata.org/V4/(S(cnbm44wtbc1v5bgrlek5lpcc))/TripPinServiceRW/](https://services.odata.org/V4/%28S%28cnbm44wtbc1v5bgrlek5lpcc%29%29/TripPinServiceRW/)  ## Entity Data Model ![ER Diagram](https://yuml.me/diagram/class/[City],[Location],[Location]++-[City],[Location]^[EventLocation],[Location]^[AirportLocation],[Photo{bg:lightslategray}],[Person{bg:lightslategray}],[Person]++-*[Location],[Person]++-0..1[PersonGender],[Person]-*>[Person],[Person]++-*>[Trip],[Person]-0..1>[Photo],[Airline{bg:lightslategray}],[Airport{bg:lightslategray}],[Airport]++-[AirportLocation],[PlanItem{bg:lightslategray}],[PlanItem]^[PublicTransportation{bg:lightslategray}],[PublicTransportation]^[Flight{bg:lightslategray}],[Flight]->[Airport],[Flight]->[Airport],[Flight]->[Airline],[PlanItem]^[Event{bg:lightslategray}],[Event]++-[EventLocation],[Trip{bg:lightslategray}],[Trip]-*>[Photo],[Trip]++-*>[PlanItem],[ResetDataSource{bg:lawngreen}],[GetNearestAirport{bg:lawngreen}]->[Airport],[Me%20{bg:lawngreen}]++->[Person],[Airports%20{bg:lawngreen}]++-*>[Airport],[Airlines%20{bg:lawngreen}]++-*>[Airline],[People%20{bg:lawngreen}]++-*>[Person],[Photos%20{bg:lawngreen}]++-*>[Photo])  ### Legend ![Legend](https://yuml.me/diagram/plain;dir:TB;scale:60/class/[External.Type{bg:whitesmoke}],[ComplexType],[EntityType{bg:lightslategray}],[EntitySet/Singleton/Operation{bg:lawngreen}])
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.odata.trippin.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import org.odata.trippin.client.GeoPoint;
import org.odata.trippin.client.MicrosoftODataSampleServiceModelsTripPinCityUpdate;
/**
 * MicrosoftODataSampleServiceModelsTripPinAirportLocationUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-03T16:45:47.437495+02:00[Europe/Zurich]")
public class MicrosoftODataSampleServiceModelsTripPinAirportLocationUpdate implements AnyOfMicrosoftODataSampleServiceModelsTripPinLocationUpdate {
  @JsonProperty("Address")
  private String address = null;

  @JsonProperty("City")
  private MicrosoftODataSampleServiceModelsTripPinCityUpdate city = null;

  @JsonProperty("Loc")
  private GeoPoint loc = null;

  public MicrosoftODataSampleServiceModelsTripPinAirportLocationUpdate address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public MicrosoftODataSampleServiceModelsTripPinAirportLocationUpdate city(MicrosoftODataSampleServiceModelsTripPinCityUpdate city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  public MicrosoftODataSampleServiceModelsTripPinCityUpdate getCity() {
    return city;
  }

  public void setCity(MicrosoftODataSampleServiceModelsTripPinCityUpdate city) {
    this.city = city;
  }

  public MicrosoftODataSampleServiceModelsTripPinAirportLocationUpdate loc(GeoPoint loc) {
    this.loc = loc;
    return this;
  }

   /**
   * Get loc
   * @return loc
  **/
  public GeoPoint getLoc() {
    return loc;
  }

  public void setLoc(GeoPoint loc) {
    this.loc = loc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftODataSampleServiceModelsTripPinAirportLocationUpdate microsoftODataSampleServiceModelsTripPinAirportLocationUpdate = (MicrosoftODataSampleServiceModelsTripPinAirportLocationUpdate) o;
    return Objects.equals(this.address, microsoftODataSampleServiceModelsTripPinAirportLocationUpdate.address) &&
        Objects.equals(this.city, microsoftODataSampleServiceModelsTripPinAirportLocationUpdate.city) &&
        Objects.equals(this.loc, microsoftODataSampleServiceModelsTripPinAirportLocationUpdate.loc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, city, loc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftODataSampleServiceModelsTripPinAirportLocationUpdate {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    loc: ").append(toIndentedString(loc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
