/*
 * TripPin service is a sample service for OData V4.
 * This service is located at [https://services.odata.org/V4/(S(cnbm44wtbc1v5bgrlek5lpcc))/TripPinServiceRW/](https://services.odata.org/V4/%28S%28cnbm44wtbc1v5bgrlek5lpcc%29%29/TripPinServiceRW/)  ## Entity Data Model ![ER Diagram](https://yuml.me/diagram/class/[City],[Location],[Location]++-[City],[Location]^[EventLocation],[Location]^[AirportLocation],[Photo{bg:lightslategray}],[Person{bg:lightslategray}],[Person]++-*[Location],[Person]++-0..1[PersonGender],[Person]-*>[Person],[Person]++-*>[Trip],[Person]-0..1>[Photo],[Airline{bg:lightslategray}],[Airport{bg:lightslategray}],[Airport]++-[AirportLocation],[PlanItem{bg:lightslategray}],[PlanItem]^[PublicTransportation{bg:lightslategray}],[PublicTransportation]^[Flight{bg:lightslategray}],[Flight]->[Airport],[Flight]->[Airport],[Flight]->[Airline],[PlanItem]^[Event{bg:lightslategray}],[Event]++-[EventLocation],[Trip{bg:lightslategray}],[Trip]-*>[Photo],[Trip]++-*>[PlanItem],[ResetDataSource{bg:lawngreen}],[GetNearestAirport{bg:lawngreen}]->[Airport],[Me%20{bg:lawngreen}]++->[Person],[Airports%20{bg:lawngreen}]++-*>[Airport],[Airlines%20{bg:lawngreen}]++-*>[Airline],[People%20{bg:lawngreen}]++-*>[Person],[Photos%20{bg:lawngreen}]++-*>[Photo])  ### Legend ![Legend](https://yuml.me/diagram/plain;dir:TB;scale:60/class/[External.Type{bg:whitesmoke}],[ComplexType],[EntityType{bg:lightslategray}],[EntitySet/Singleton/Operation{bg:lawngreen}])
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.odata.trippin.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.odata.trippin.client.MicrosoftODataSampleServiceModelsTripPinLocationCreate;
import org.odata.trippin.client.MicrosoftODataSampleServiceModelsTripPinPersonCreate;
import org.odata.trippin.client.MicrosoftODataSampleServiceModelsTripPinTripCreate;
/**
 * MicrosoftODataSampleServiceModelsTripPinPersonCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-03T16:45:47.437495+02:00[Europe/Zurich]")
public class MicrosoftODataSampleServiceModelsTripPinPersonCreate {
  @JsonProperty("FirstName")
  private String firstName = null;

  @JsonProperty("LastName")
  private String lastName = null;

  @JsonProperty("Emails")
  private List<String> emails = null;

  @JsonProperty("AddressInfo")
  private List<MicrosoftODataSampleServiceModelsTripPinLocationCreate> addressInfo = null;

  @JsonProperty("Gender")
  private AnyOfMicrosoftODataSampleServiceModelsTripPinPersonCreateGender gender = null;

  @JsonProperty("Friends")
  private List<MicrosoftODataSampleServiceModelsTripPinPersonCreate> friends = null;

  @JsonProperty("Trips")
  private List<MicrosoftODataSampleServiceModelsTripPinTripCreate> trips = null;

  @JsonProperty("Photo")
  private AnyOfMicrosoftODataSampleServiceModelsTripPinPersonCreatePhoto photo = null;

  public MicrosoftODataSampleServiceModelsTripPinPersonCreate firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public MicrosoftODataSampleServiceModelsTripPinPersonCreate lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public MicrosoftODataSampleServiceModelsTripPinPersonCreate emails(List<String> emails) {
    this.emails = emails;
    return this;
  }

  public MicrosoftODataSampleServiceModelsTripPinPersonCreate addEmailsItem(String emailsItem) {
    if (this.emails == null) {
      this.emails = new ArrayList<>();
    }
    this.emails.add(emailsItem);
    return this;
  }

   /**
   * Get emails
   * @return emails
  **/
  public List<String> getEmails() {
    return emails;
  }

  public void setEmails(List<String> emails) {
    this.emails = emails;
  }

  public MicrosoftODataSampleServiceModelsTripPinPersonCreate addressInfo(List<MicrosoftODataSampleServiceModelsTripPinLocationCreate> addressInfo) {
    this.addressInfo = addressInfo;
    return this;
  }

  public MicrosoftODataSampleServiceModelsTripPinPersonCreate addAddressInfoItem(MicrosoftODataSampleServiceModelsTripPinLocationCreate addressInfoItem) {
    if (this.addressInfo == null) {
      this.addressInfo = new ArrayList<>();
    }
    this.addressInfo.add(addressInfoItem);
    return this;
  }

   /**
   * Get addressInfo
   * @return addressInfo
  **/
  public List<MicrosoftODataSampleServiceModelsTripPinLocationCreate> getAddressInfo() {
    return addressInfo;
  }

  public void setAddressInfo(List<MicrosoftODataSampleServiceModelsTripPinLocationCreate> addressInfo) {
    this.addressInfo = addressInfo;
  }

  public MicrosoftODataSampleServiceModelsTripPinPersonCreate gender(AnyOfMicrosoftODataSampleServiceModelsTripPinPersonCreateGender gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  public AnyOfMicrosoftODataSampleServiceModelsTripPinPersonCreateGender getGender() {
    return gender;
  }

  public void setGender(AnyOfMicrosoftODataSampleServiceModelsTripPinPersonCreateGender gender) {
    this.gender = gender;
  }

  public MicrosoftODataSampleServiceModelsTripPinPersonCreate friends(List<MicrosoftODataSampleServiceModelsTripPinPersonCreate> friends) {
    this.friends = friends;
    return this;
  }

  public MicrosoftODataSampleServiceModelsTripPinPersonCreate addFriendsItem(MicrosoftODataSampleServiceModelsTripPinPersonCreate friendsItem) {
    if (this.friends == null) {
      this.friends = new ArrayList<>();
    }
    this.friends.add(friendsItem);
    return this;
  }

   /**
   * Get friends
   * @return friends
  **/
  public List<MicrosoftODataSampleServiceModelsTripPinPersonCreate> getFriends() {
    return friends;
  }

  public void setFriends(List<MicrosoftODataSampleServiceModelsTripPinPersonCreate> friends) {
    this.friends = friends;
  }

  public MicrosoftODataSampleServiceModelsTripPinPersonCreate trips(List<MicrosoftODataSampleServiceModelsTripPinTripCreate> trips) {
    this.trips = trips;
    return this;
  }

  public MicrosoftODataSampleServiceModelsTripPinPersonCreate addTripsItem(MicrosoftODataSampleServiceModelsTripPinTripCreate tripsItem) {
    if (this.trips == null) {
      this.trips = new ArrayList<>();
    }
    this.trips.add(tripsItem);
    return this;
  }

   /**
   * Get trips
   * @return trips
  **/
  public List<MicrosoftODataSampleServiceModelsTripPinTripCreate> getTrips() {
    return trips;
  }

  public void setTrips(List<MicrosoftODataSampleServiceModelsTripPinTripCreate> trips) {
    this.trips = trips;
  }

  public MicrosoftODataSampleServiceModelsTripPinPersonCreate photo(AnyOfMicrosoftODataSampleServiceModelsTripPinPersonCreatePhoto photo) {
    this.photo = photo;
    return this;
  }

   /**
   * Get photo
   * @return photo
  **/
  public AnyOfMicrosoftODataSampleServiceModelsTripPinPersonCreatePhoto getPhoto() {
    return photo;
  }

  public void setPhoto(AnyOfMicrosoftODataSampleServiceModelsTripPinPersonCreatePhoto photo) {
    this.photo = photo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftODataSampleServiceModelsTripPinPersonCreate microsoftODataSampleServiceModelsTripPinPersonCreate = (MicrosoftODataSampleServiceModelsTripPinPersonCreate) o;
    return Objects.equals(this.firstName, microsoftODataSampleServiceModelsTripPinPersonCreate.firstName) &&
        Objects.equals(this.lastName, microsoftODataSampleServiceModelsTripPinPersonCreate.lastName) &&
        Objects.equals(this.emails, microsoftODataSampleServiceModelsTripPinPersonCreate.emails) &&
        Objects.equals(this.addressInfo, microsoftODataSampleServiceModelsTripPinPersonCreate.addressInfo) &&
        Objects.equals(this.gender, microsoftODataSampleServiceModelsTripPinPersonCreate.gender) &&
        Objects.equals(this.friends, microsoftODataSampleServiceModelsTripPinPersonCreate.friends) &&
        Objects.equals(this.trips, microsoftODataSampleServiceModelsTripPinPersonCreate.trips) &&
        Objects.equals(this.photo, microsoftODataSampleServiceModelsTripPinPersonCreate.photo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, emails, addressInfo, gender, friends, trips, photo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftODataSampleServiceModelsTripPinPersonCreate {\n");
    
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("    addressInfo: ").append(toIndentedString(addressInfo)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    friends: ").append(toIndentedString(friends)).append("\n");
    sb.append("    trips: ").append(toIndentedString(trips)).append("\n");
    sb.append("    photo: ").append(toIndentedString(photo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
