/*
 * TripPin service is a sample service for OData V4.
 * This service is located at [https://services.odata.org/V4/(S(cnbm44wtbc1v5bgrlek5lpcc))/TripPinServiceRW/](https://services.odata.org/V4/%28S%28cnbm44wtbc1v5bgrlek5lpcc%29%29/TripPinServiceRW/)  ## Entity Data Model ![ER Diagram](https://yuml.me/diagram/class/[City],[Location],[Location]++-[City],[Location]^[EventLocation],[Location]^[AirportLocation],[Photo{bg:lightslategray}],[Person{bg:lightslategray}],[Person]++-*[Location],[Person]++-0..1[PersonGender],[Person]-*>[Person],[Person]++-*>[Trip],[Person]-0..1>[Photo],[Airline{bg:lightslategray}],[Airport{bg:lightslategray}],[Airport]++-[AirportLocation],[PlanItem{bg:lightslategray}],[PlanItem]^[PublicTransportation{bg:lightslategray}],[PublicTransportation]^[Flight{bg:lightslategray}],[Flight]->[Airport],[Flight]->[Airport],[Flight]->[Airline],[PlanItem]^[Event{bg:lightslategray}],[Event]++-[EventLocation],[Trip{bg:lightslategray}],[Trip]-*>[Photo],[Trip]++-*>[PlanItem],[ResetDataSource{bg:lawngreen}],[GetNearestAirport{bg:lawngreen}]->[Airport],[Me%20{bg:lawngreen}]++->[Person],[Airports%20{bg:lawngreen}]++-*>[Airport],[Airlines%20{bg:lawngreen}]++-*>[Airline],[People%20{bg:lawngreen}]++-*>[Person],[Photos%20{bg:lawngreen}]++-*>[Photo])  ### Legend ![Legend](https://yuml.me/diagram/plain;dir:TB;scale:60/class/[External.Type{bg:whitesmoke}],[ComplexType],[EntityType{bg:lightslategray}],[EntitySet/Singleton/Operation{bg:lawngreen}])
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.odata.trippin.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import org.odata.trippin.client.MicrosoftODataSampleServiceModelsTripPinAirportLocation;
/**
 * MicrosoftODataSampleServiceModelsTripPinAirport
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-03T16:45:47.437495+02:00[Europe/Zurich]")
public class MicrosoftODataSampleServiceModelsTripPinAirport {
  @JsonProperty("IcaoCode")
  private String icaoCode = null;

  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("IataCode")
  private String iataCode = null;

  @JsonProperty("Location")
  private MicrosoftODataSampleServiceModelsTripPinAirportLocation location = null;

  public MicrosoftODataSampleServiceModelsTripPinAirport icaoCode(String icaoCode) {
    this.icaoCode = icaoCode;
    return this;
  }

   /**
   * Get icaoCode
   * @return icaoCode
  **/
  public String getIcaoCode() {
    return icaoCode;
  }

  public void setIcaoCode(String icaoCode) {
    this.icaoCode = icaoCode;
  }

  public MicrosoftODataSampleServiceModelsTripPinAirport name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MicrosoftODataSampleServiceModelsTripPinAirport iataCode(String iataCode) {
    this.iataCode = iataCode;
    return this;
  }

   /**
   * Get iataCode
   * @return iataCode
  **/
  public String getIataCode() {
    return iataCode;
  }

  public void setIataCode(String iataCode) {
    this.iataCode = iataCode;
  }

  public MicrosoftODataSampleServiceModelsTripPinAirport location(MicrosoftODataSampleServiceModelsTripPinAirportLocation location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  public MicrosoftODataSampleServiceModelsTripPinAirportLocation getLocation() {
    return location;
  }

  public void setLocation(MicrosoftODataSampleServiceModelsTripPinAirportLocation location) {
    this.location = location;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftODataSampleServiceModelsTripPinAirport microsoftODataSampleServiceModelsTripPinAirport = (MicrosoftODataSampleServiceModelsTripPinAirport) o;
    return Objects.equals(this.icaoCode, microsoftODataSampleServiceModelsTripPinAirport.icaoCode) &&
        Objects.equals(this.name, microsoftODataSampleServiceModelsTripPinAirport.name) &&
        Objects.equals(this.iataCode, microsoftODataSampleServiceModelsTripPinAirport.iataCode) &&
        Objects.equals(this.location, microsoftODataSampleServiceModelsTripPinAirport.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(icaoCode, name, iataCode, location);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftODataSampleServiceModelsTripPinAirport {\n");
    
    sb.append("    icaoCode: ").append(toIndentedString(icaoCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    iataCode: ").append(toIndentedString(iataCode)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
