package com.axonivy.connectivity.soap.service.client;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.6.11
 * 2026-06-17T07:38:27.636+02:00
 * Generated source version: 3.6.11
 *
 */
@WebService(targetNamespace = "http://service.soap.connectivity.axonivy.com/", name = "PersonService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.636+02:00", comments = "Apache CXF 3.6.11")
public interface PersonService {

    @WebMethod
    @WebResult(name = "addPersonResponse", targetNamespace = "http://service.soap.connectivity.axonivy.com/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.636+02:00")
    public AddPersonResponse addPerson(

        @WebParam(partName = "parameters", name = "addPerson", targetNamespace = "http://service.soap.connectivity.axonivy.com/")
        AddPerson parameters
    ) throws WebServiceProcessTechnicalException;

    @WebMethod
    @WebResult(name = "getPersonsResponse", targetNamespace = "http://service.soap.connectivity.axonivy.com/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.636+02:00")
    public GetPersonsResponse getPersons(

        @WebParam(partName = "parameters", name = "getPersons", targetNamespace = "http://service.soap.connectivity.axonivy.com/")
        GetPersons parameters
    ) throws WebServiceProcessTechnicalException;

    @WebMethod
    @WebResult(name = "deletePersonResponse", targetNamespace = "http://service.soap.connectivity.axonivy.com/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.636+02:00")
    public DeletePersonResponse deletePerson(

        @WebParam(partName = "parameters", name = "deletePerson", targetNamespace = "http://service.soap.connectivity.axonivy.com/")
        DeletePerson parameters
    ) throws WebServiceProcessTechnicalException;
}
