/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ivy.local.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ProcessStartBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-16T14:11:32.936281+02:00[Europe/Zurich]")
public class ProcessStartBean {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("activatorName")
  private String activatorName = null;

  @JsonProperty("fullRequestPath")
  private String fullRequestPath = null;

  public ProcessStartBean id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ProcessStartBean name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ProcessStartBean description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ProcessStartBean activatorName(String activatorName) {
    this.activatorName = activatorName;
    return this;
  }

   /**
   * Get activatorName
   * @return activatorName
  **/
  public String getActivatorName() {
    return activatorName;
  }

  public void setActivatorName(String activatorName) {
    this.activatorName = activatorName;
  }

  public ProcessStartBean fullRequestPath(String fullRequestPath) {
    this.fullRequestPath = fullRequestPath;
    return this;
  }

   /**
   * Get fullRequestPath
   * @return fullRequestPath
  **/
  public String getFullRequestPath() {
    return fullRequestPath;
  }

  public void setFullRequestPath(String fullRequestPath) {
    this.fullRequestPath = fullRequestPath;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessStartBean processStartBean = (ProcessStartBean) o;
    return Objects.equals(this.id, processStartBean.id) &&
        Objects.equals(this.name, processStartBean.name) &&
        Objects.equals(this.description, processStartBean.description) &&
        Objects.equals(this.activatorName, processStartBean.activatorName) &&
        Objects.equals(this.fullRequestPath, processStartBean.fullRequestPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, activatorName, fullRequestPath);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessStartBean {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    activatorName: ").append(toIndentedString(activatorName)).append("\n");
    sb.append("    fullRequestPath: ").append(toIndentedString(fullRequestPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
