/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ivy.local.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import ivy.local.client.CaseBean;
import java.time.OffsetDateTime;
/**
 * TaskBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-16T14:11:32.936281+02:00[Europe/Zurich]")
public class TaskBean {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("startTimeStamp")
  private OffsetDateTime startTimeStamp = null;

  @JsonProperty("expiryTimeStamp")
  private OffsetDateTime expiryTimeStamp = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("state")
  private Integer state = null;

  @JsonProperty("activatorName")
  private String activatorName = null;

  @JsonProperty("fullRequestPath")
  private String fullRequestPath = null;

  @JsonProperty("offline")
  private Boolean offline = null;

  @JsonProperty("case")
  private CaseBean _case = null;

  public TaskBean id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TaskBean name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TaskBean description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TaskBean startTimeStamp(OffsetDateTime startTimeStamp) {
    this.startTimeStamp = startTimeStamp;
    return this;
  }

   /**
   * Get startTimeStamp
   * @return startTimeStamp
  **/
  public OffsetDateTime getStartTimeStamp() {
    return startTimeStamp;
  }

  public void setStartTimeStamp(OffsetDateTime startTimeStamp) {
    this.startTimeStamp = startTimeStamp;
  }

  public TaskBean expiryTimeStamp(OffsetDateTime expiryTimeStamp) {
    this.expiryTimeStamp = expiryTimeStamp;
    return this;
  }

   /**
   * Get expiryTimeStamp
   * @return expiryTimeStamp
  **/
  public OffsetDateTime getExpiryTimeStamp() {
    return expiryTimeStamp;
  }

  public void setExpiryTimeStamp(OffsetDateTime expiryTimeStamp) {
    this.expiryTimeStamp = expiryTimeStamp;
  }

  public TaskBean priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public TaskBean state(Integer state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  public Integer getState() {
    return state;
  }

  public void setState(Integer state) {
    this.state = state;
  }

  public TaskBean activatorName(String activatorName) {
    this.activatorName = activatorName;
    return this;
  }

   /**
   * Get activatorName
   * @return activatorName
  **/
  public String getActivatorName() {
    return activatorName;
  }

  public void setActivatorName(String activatorName) {
    this.activatorName = activatorName;
  }

  public TaskBean fullRequestPath(String fullRequestPath) {
    this.fullRequestPath = fullRequestPath;
    return this;
  }

   /**
   * Get fullRequestPath
   * @return fullRequestPath
  **/
  public String getFullRequestPath() {
    return fullRequestPath;
  }

  public void setFullRequestPath(String fullRequestPath) {
    this.fullRequestPath = fullRequestPath;
  }

  public TaskBean offline(Boolean offline) {
    this.offline = offline;
    return this;
  }

   /**
   * Get offline
   * @return offline
  **/
  public Boolean isOffline() {
    return offline;
  }

  public void setOffline(Boolean offline) {
    this.offline = offline;
  }

  public TaskBean _case(CaseBean _case) {
    this._case = _case;
    return this;
  }

   /**
   * Get _case
   * @return _case
  **/
  public CaseBean getCase() {
    return _case;
  }

  public void setCase(CaseBean _case) {
    this._case = _case;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskBean taskBean = (TaskBean) o;
    return Objects.equals(this.id, taskBean.id) &&
        Objects.equals(this.name, taskBean.name) &&
        Objects.equals(this.description, taskBean.description) &&
        Objects.equals(this.startTimeStamp, taskBean.startTimeStamp) &&
        Objects.equals(this.expiryTimeStamp, taskBean.expiryTimeStamp) &&
        Objects.equals(this.priority, taskBean.priority) &&
        Objects.equals(this.state, taskBean.state) &&
        Objects.equals(this.activatorName, taskBean.activatorName) &&
        Objects.equals(this.fullRequestPath, taskBean.fullRequestPath) &&
        Objects.equals(this.offline, taskBean.offline) &&
        Objects.equals(this._case, taskBean._case);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, startTimeStamp, expiryTimeStamp, priority, state, activatorName, fullRequestPath, offline, _case);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskBean {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    startTimeStamp: ").append(toIndentedString(startTimeStamp)).append("\n");
    sb.append("    expiryTimeStamp: ").append(toIndentedString(expiryTimeStamp)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    activatorName: ").append(toIndentedString(activatorName)).append("\n");
    sb.append("    fullRequestPath: ").append(toIndentedString(fullRequestPath)).append("\n");
    sb.append("    offline: ").append(toIndentedString(offline)).append("\n");
    sb.append("    _case: ").append(toIndentedString(_case)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
