package com.smartbear.sample.test.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-04-12T12:53:04.179+02:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://smartbear.com", name = "SampleWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SampleWebServiceSoap {

    /**
     * This method uses an object as a parameter.
     */
    @WebMethod(operationName = "SetSampleObject", action = "http://smartbear.com/SetSampleObject")
    @WebResult(name = "SetSampleObjectResponse", targetNamespace = "http://smartbear.com", partName = "parameters")
    public SetSampleObjectResponse setSampleObject(
        @WebParam(partName = "parameters", name = "SetSampleObject", targetNamespace = "http://smartbear.com")
        SetSampleObject parameters
    );

    /**
     * This method returns a string value.
     */
    @WebMethod(operationName = "HelloWorld", action = "http://smartbear.com/HelloWorld")
    @WebResult(name = "HelloWorldResponse", targetNamespace = "http://smartbear.com", partName = "parameters")
    public HelloWorldResponse helloWorld(
        @WebParam(partName = "parameters", name = "HelloWorld", targetNamespace = "http://smartbear.com")
        HelloWorld parameters
    );

    /**
     * This method returns the current system time.
     */
    @WebMethod(operationName = "GetCurrentTime", action = "http://smartbear.com/GetCurrentTime")
    @WebResult(name = "GetCurrentTimeResponse", targetNamespace = "http://smartbear.com", partName = "parameters")
    public GetCurrentTimeResponse getCurrentTime(
        @WebParam(partName = "parameters", name = "GetCurrentTime", targetNamespace = "http://smartbear.com")
        GetCurrentTime parameters
    );

    /**
     * This method returns an array of integer values.
     */
    @WebMethod(operationName = "GetArray", action = "http://smartbear.com/GetArray")
    @WebResult(name = "GetArrayResponse", targetNamespace = "http://smartbear.com", partName = "parameters")
    public GetArrayResponse getArray(
        @WebParam(partName = "parameters", name = "GetArray", targetNamespace = "http://smartbear.com")
        GetArray parameters
    );

    /**
     * This method returns an object.
     */
    @WebMethod(operationName = "GetSampleObject", action = "http://smartbear.com/GetSampleObject")
    @WebResult(name = "GetSampleObjectResponse", targetNamespace = "http://smartbear.com", partName = "parameters")
    public GetSampleObjectResponse getSampleObject(
        @WebParam(partName = "parameters", name = "GetSampleObject", targetNamespace = "http://smartbear.com")
        GetSampleObject parameters
    );

    /**
     * This method returns an object that is an XML node.
     */
    @WebMethod(operationName = "GetXmlData", action = "http://smartbear.com/GetXmlData")
    @WebResult(name = "GetXmlDataResponse", targetNamespace = "http://smartbear.com", partName = "parameters")
    public GetXmlDataResponse getXmlData(
        @WebParam(partName = "parameters", name = "GetXmlData", targetNamespace = "http://smartbear.com")
        GetXmlData parameters
    );
}
