package soap.intercepted.client.person.ivyteam.ch.client;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2023-09-13T08:45:29.483+02:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://service.soap.connectivity.axonivy.com/", name = "PersonService")
@XmlSeeAlso({intercepted.client.person.ivyteam.ch.client.ObjectFactory.class, org.w3._2001.xmlschema.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-09-13T08:45:29.483+02:00", comments = "Apache CXF 3.5.3")
public interface PersonService {

    @WebMethod
    @WebResult(name = "addPersonResponse", targetNamespace = "http://service.soap.connectivity.axonivy.com/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-09-13T08:45:29.483+02:00")
    public AddPersonResponse addPerson(

        @WebParam(partName = "parameters", name = "addPerson", targetNamespace = "http://service.soap.connectivity.axonivy.com/")
        AddPerson parameters
    ) throws WebServiceProcessTechnicalException;

    @WebMethod
    @WebResult(name = "getPersonsResponse", targetNamespace = "http://service.soap.connectivity.axonivy.com/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-09-13T08:45:29.483+02:00")
    public GetPersonsResponse getPersons(

        @WebParam(partName = "parameters", name = "getPersons", targetNamespace = "http://service.soap.connectivity.axonivy.com/")
        GetPersons parameters
    ) throws WebServiceProcessTechnicalException;

    @WebMethod
    @WebResult(name = "deletePersonResponse", targetNamespace = "http://service.soap.connectivity.axonivy.com/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2023-09-13T08:45:29.483+02:00")
    public DeletePersonResponse deletePerson(

        @WebParam(partName = "parameters", name = "deletePerson", targetNamespace = "http://service.soap.connectivity.axonivy.com/")
        DeletePerson parameters
    ) throws WebServiceProcessTechnicalException;
}
